### ISSUE TITLE
My Last Coworking Event

### ISSUE THREAD

**Issue by sroberts** [central-pa-cowork/cowork-planning#15]
So as some of you know I am leaving you fine folks to move to Ohio because I'm a good husband and move miserable places to support my wife's dreams. (Mostly joking)

As it happens one thing I've never done in all my time here, and all my time spent there, is take a [tour of the Troegs Brewery](http://www.troegs.com/brewery_tours.aspx). This needs to be corrected:
## What I'm proposing:
- Meet at Troegs around 1pm on Monday, June 16. 
- Lunch and a beverage.
- I have 5 spots currently for the 2:30 PM tour (Though I can get more):
  - [x] Myself
  - [x] @daverobertson 
  - [x] @lmarburger 
  - [x] @danthompson
  - [x] @hellohynes
  - [x] @jglovier 

WE CAN GET MORE!

Hows that sound gents? Who's game?

**Comment by lfarenw** [comment]
Bummer! I'll be with my son that day and he's too young for brewery tours.
:)

But best of luck to you and your wife's dream of being a comedian in Ohio.

**Comment by sroberts** [comment]
Anyone else interested in that last spot? @hellohynes @jglovier? We can bump up another spot if you both wanna make it down.

**Comment by hellohynes** [comment]
Yeah I could do that.

**Comment by jglovier** [comment]
YES PLEASE!!!!!

**Comment by sroberts** [comment]
@jglovier Requested another spot.

**Comment by sroberts** [comment]
Success!

**Comment by jglovier** [comment]
HUZZAH!!

![img](http://gifs.joelglovier.com/excited/42-Snoop-Bounce.gif)

**Comment by jglovier** [comment]
To be clear - is this at the facility in Hershey or on Paxton Street?

**Comment by jglovier** [comment]
...okay so I just discovered that the Paxton Street location is no more - and was actually replaced by the Hershey facility. DERP DERP see you thur DERP.

**Comment by lmarburger** [comment]
That was fun!

![](http://gifs.joelglovier.com/fail/party-wipeout.gif)
