### ISSUE TITLE
Thursday & Friday the 7th & 8th of August

### ISSUE THREAD

**Issue by sroberts** [central-pa-cowork/cowork-planning#23]
So I'll be back in town the end of this week and likely up at the fine Little Amps establishment. Would love to share some :coffee: with you fine folks...

![x9a5n3r](https://cloud.githubusercontent.com/assets/44774/3812628/0fa001be-1cac-11e4-983f-39c61330c817.gif)

Well not share... we'd each have our own... It's more of a metaphorical sharing... I could also be talked into :beers: at Troegs.

**Comment by lmarburger** [comment]
I'm free both days! My personal preference would be slightly in favor of Little Amps Friday morning.

**Comment by dustinleer** [comment]
If I were to join Friday would be the best option.
![its-friday-meme-and-lol](https://cloud.githubusercontent.com/assets/1885540/3813077/1254738c-1cb0-11e4-8d26-98770e30ece4.jpg)

**Comment by danthompson** [comment]
@sroberts you know where I can be found. :wink:

**Comment by sroberts** [comment]
I'll likely be there both days, so use that as you will...

@danthompson: Avoiding us all? #rimshot

**Comment by sroberts** [comment]
I'll likely be there both days, so use that as you will...

@danthompson: Avoiding us all? #rimshot

**Comment by sroberts** [comment]
I'll likely be there both days, so use that as you will...

@danthompson: Avoiding us all? #rimshot

**Comment by lmarburger** [comment]
Thanks for sending that 3 times, @sroberts. I missed it the first 2.

**Comment by dustinleer** [comment]
![joe-biden-laughing](https://cloud.githubusercontent.com/assets/1885540/3815696/b4bc075e-1cc7-11e4-83e1-98d1053131bb.gif)

**Comment by sroberts** [comment]
I figured you generally have to ask @danthompson at least three times to get him to come out once... so...

![this panda is a dick - imgur image](https://cloud.githubusercontent.com/assets/44774/3815889/c7a32c74-1cc9-11e4-9a35-8ee31206b810.gif)

**Comment by danthompson** [comment]
Yep, three is the minimum to get me out.
![movn](https://cloud.githubusercontent.com/assets/68388/3816281/1f93a1b8-1ccd-11e4-908c-b0a97eb0c8bd.gif)

**Comment by lmarburger** [comment]
Change of plans. I'll be there this morning. See you there, @sroberts!

**Comment by sroberts** [comment]
@lmarburger Change of plans myself. After spending 7.5 hours in a VW dealership to get an oil change (yup... that bad) I'm only leaving today.

**Comment by daverobertson** [comment]
Change your own oil! #manup

(only takes 2 hours)

**Comment by sroberts** [comment]
![its-not-gonna-happen](https://cloud.githubusercontent.com/assets/44774/3843133/a1fe7544-1e3d-11e4-8775-db776d99b948.gif)
