### ISSUE TITLE
Cowork week of 8/18

### ISSUE THREAD

**Issue by jglovier** [central-pa-cowork/cowork-planning#24]
Anyone want to cowork today?

**Comment by lmarburger** [comment]
I'm game. Was planning to go to Folklore this morning as per usual.

**Comment by daverobertson** [comment]
I'll be there.

**Comment by lmarburger** [comment]
Turns out @hellohynes, @jglovier, and I ended up at Little Amps 1.

**Comment by dustinleer** [comment]
Which is 1?

**Comment by lmarburger** [comment]
The one on Green and Muench Streets.
