### ISSUE TITLE
08.29.14

### ISSUE THREAD

**Issue by dustinleer** [central-pa-cowork/cowork-planning#25]
Anyone up for coworking today?

**Comment by dustinleer** [comment]
_crickets_ @jglovier @hellohynes @lmarburger @daverobertson anyone?

**Comment by hellohynes** [comment]
Sorry. Been pretty busy this week. And I’m on vacation next week!

Definitely when I get back.

**Comment by jglovier** [comment]
Out of town today. :car: Thanks anyway.

**Comment by dustinleer** [comment]
Womp womp :thumbsdown:
