### ISSUE TITLE
Week of 3/17/14

### ISSUE THREAD

**Issue by sroberts** [central-pa-cowork/cowork-planning#3]
First of all:

![](http://i.imgur.com/ajHRNAu.gif)

Wasn't that adorable? Second of all: Who's working where this week?

I'm at Amps RIGHT NOW!!! :coffee: But will probably also go out Wed & maybe Friday? Though I could be convinced to make other plans.

**Comment by iamkyle** [comment]
I'll be at Prince St. Tomorrow & Thurs.

**Comment by lmarburger** [comment]
[Adorable!](https://www.youtube.com/watch?v=HK0l2tqFDvM)

I'm at Folklore RIGHT NOW!!! :coffee: I drove around a bunch last week so I think I'm going to hit Folklore only once more this week. Probably Thursday or Friday.

**Comment by hellohynes** [comment]
I’m in London. Feel free to join me.

**Comment by danthompson** [comment]
I need to hit Folklore this week. (out of beans). But I'd be up for LA too.

**Comment by sroberts** [comment]
I'm gonna be doing LA1 tomorrow for beans myself. :coffee:

**Comment by lmarburger** [comment]
See everyone over at #4.
