### ISSUE TITLE
Week of 3/16

### ISSUE THREAD

**Issue by jglovier** [central-pa-cowork/cowork-planning#48]
Who wants to cowork this week? I have a car all week so I'm feelin to get out of this house! Any day works for me.

![wooo](https://cloud.githubusercontent.com/assets/1319791/6665656/61f06e80-cbb2-11e4-944e-6c24dbd3724a.gif)

**Comment by dustinleer** [comment]
I'd be down for Friday.

![2zox5](https://cloud.githubusercontent.com/assets/1885540/6666117/91e762ec-cbb7-11e4-9355-beba99861c07.gif)

**Comment by dustinleer** [comment]
Well ok then, this thread is dead. :skull: 

![tumblr_inline_mgv01qbwpt1r5c8sb](https://cloud.githubusercontent.com/assets/1885540/6735001/c1efb4c2-ce31-11e4-8903-dbbed1726d5b.gif)

**Comment by hellohynes** [comment]
Sorry — crazy week for me. Meetings almost every day. Le sigh

**Comment by hellohynes** [comment]
I blame this on @lmarburger though.

**Comment by jglovier** [comment]
Yeah I have a couple meetings tomorrow too. :frowning:

**Comment by jglovier** [comment]
Also - how is it Thursday already???

**Comment by dustinleer** [comment]
MAGIC!
![shia-labeouf-magic-gif](https://cloud.githubusercontent.com/assets/1885540/6738818/daafccf4-ce4a-11e4-826c-9af0668b56b8.gif)

**Comment by lmarburger** [comment]
I could probably do Cornerstone tomorrow or next week. Need to run some errands up that way.
