### ISSUE TITLE
Week of 3/23

### ISSUE THREAD

**Issue by dustinleer** [central-pa-cowork/cowork-planning#49]
Anyone down for co-working on Friday?

**Comment by jglovier** [comment]
I'm speaking at [Squares Conf](http://squaresconference.com/) in Texas Friday. :frowning:

**Comment by dustinleer** [comment]
@jglovier I thought you might be. Spring is coming though, we gotta get together during the warmer parts of the year . :smile:

**Comment by hellohynes** [comment]
I'm in NYC this week. 😮

**Comment by dustinleer** [comment]
Oh snap!
