### ISSUE TITLE
Week of 3/30

### ISSUE THREAD

**Issue by dustinleer** [central-pa-cowork/cowork-planning#50]
Ok let's do this thing! My last day at the office is Tuesday, I would be down to get together.

![imdown](https://cloud.githubusercontent.com/assets/1885540/6855466/ed251572-d3ce-11e4-8fc2-edfdcd7943c7.gif)

**Comment by jglovier** [comment]
What day works best?

**Comment by lmarburger** [comment]
I'm down Tuesday through Friday. (Morning only on Friday.)

**Comment by dustinleer** [comment]
I can do Wednesday (until lunch) or Friday.

**Comment by lmarburger** [comment]
Scheduled changed. This week won't work for me any more. :crying_cat_face:

**Comment by dustinleer** [comment]
![img](http://media1.giphy.com/media/12h4pgk1SRtLuo/giphy.gif)

**Comment by jglovier** [comment]
@wildcanon FYI you can get your links to appear by using this markdown image syntax:

```
![img](http://media1.giphy.com/media/12h4pgk1SRtLuo/giphy.gif)
```

Yeah this week is shaping up pretty nuts for me too. I have a huge deadline next week, Friday we are doing our family's Easter dinner, and Thursday I'm taking my mom to treatment. So I'm out for this week too. :confused: 

![sad-kitty](https://cloud.githubusercontent.com/assets/1319791/6919844/66911d36-d788-11e4-8a12-497bba991504.gif)

**Comment by dustinleer** [comment]
@jglovier thanks :+1: 

It's ok i'll just be over here all by myself.

![img](http://gifsec.com/wp-content/uploads/GIF/2014/04/High-five-with-myself-gif.gif)
