### ISSUE TITLE
Coworking for week of 4/21/2014

### ISSUE THREAD

**Issue by jglovier** [central-pa-cowork/cowork-planning#8]
It's midweek, but anyone want to cowork tomorrow or Friday?

**Comment by jglovier** [comment]
...with all the craziness this week I could use a good dose of personal interaction with real people™.

**Comment by danthompson** [comment]
I could be game.

**Comment by hellohynes** [comment]
Friday could work for me. Do we want to finally do a Prince St. Cafe trip?

**Comment by sroberts** [comment]
So apparently it was @hellohynes birthday this week. I request adult beverages! :beers:

**Comment by jglovier** [comment]
> So apparently it was @hellohynes birthday this week. I request adult beverages! :beers:

![yup](https://cloud.githubusercontent.com/assets/1319791/2783200/fbd16c0a-cb29-11e3-8a36-baee1c9fa52b.gif)

**Comment by hellohynes** [comment]
Actually... Anyone up for tomorrow? I wouldn't mind getting out. @jglovier Do you want me to pick you up?

**Comment by jglovier** [comment]
@hellohynes depends what time you have in mind. :smile: I'm working late tonight and sleeping in tomorrow. I don't really intend to get out of bed before 9 or 10 tomorrow. :grin:

**Comment by hellohynes** [comment]
Well… hmmmm… That does put a kink in things. I guess I could Friday still. I’d just want to get back earlier (in the afternoon).

**Comment by jglovier** [comment]
Yeah probably tomorrows not great for me. Let's aim for Friday.

**Comment by daverobertson** [comment]
Friday is wide open (so far) for me.

**Comment by sroberts** [comment]
Friday it is....

![](http://www.imagesbuddy.com/images/80/2013/08/its-friday-drinks-glitter.gif)

**Comment by hellohynes** [comment]
Where we heading?

**Comment by sroberts** [comment]
![](http://downingtowndish.com/files/2010/11/TroegsPromo_01.jpg)

**Comment by lfarenw** [comment]
If you make it to Prince St Cafe, I will be there.

On Thu, Apr 24, 2014 at 10:11 AM, Scott J. Roberts <notifications@github.com

**Comment by hellohynes** [comment]
Hmmm…. I don’t know man. It was kind of loud there last time. :)

Joel, what time should I pick you up?

## Is Larry on vacation this week or something?

Joshua Hynes
hello@joshuahynes.com

**Comment by jglovier** [comment]
@hellohynes sorry brother man, change of plans for me. I'm taking tomorrow off, although I might catch up with you guys later in the afternoon for a bit.

**Comment by hellohynes** [comment]
Ok. That's understandable. @sroberts @lmarburger @joshuamiller @daverobertson @danthompson I'll be heading down to Prince St if anyone is interested in joining. I haven't been in a while. I'll probably stick around until 2-2:30pm.
